# Generated by Django 2.2.17 on 2020-12-13 18:54

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('regular', 'regular')], max_length=20)),
            ],
        ),
    ]
